### ISSUE TITLE
Překladová tabulka

### ISSUE THREAD

**Issue by JanSuchanek** [trejjam/skoleni-13_14-11-2014#1]
Vyplatí se i tohle? Nebo je lepší vytvořit rovnou nějaký makro nebo filtr?

/\* Výpis seznamu odkazů na články např. z databáze */
{var $mask = $presenter->link('Article:default', slug => 'example')}

{foreach $articles as $article}
    <p>{$mask|replace:example:$article->slug}</p>
{/foreach}

**Comment by trejjam** [comment]
Co si pamatuji, tak to David označil jako "nečisté" řešení, které ale rozhodně na rychlosti přidá viz: https://github.com/Trejjam/skoleni-13_14-11-2014/blob/master/sandbox/app/templates/Sign/in.latte

Makro by to mělo rozhodně zhezčit/pročistit. Zatím mě napadá vytvořit něco takovéhoto:

``` php
class CacheLinkMacro extends Latte\Macros\MacroSet
{
static private $urls=[];
const ParamsPrefix="__PAR__";
static function install($compiler) {
  $cm = new self($compiler);
  $cm->addMacro('cachedLink', 'CacheLinkMacro::render(%node.word, %node.args)');
}
static function render($presenterAction, $params) {
  $key=$presenterAction.self::ParamsPrefix.implode(self::ParamsPrefix, ksort(array_keys($params)));

  $fooArr=[];
  foreach($params as $k=>$v) {
    $fooArr[$k]=self::ParamsPrefix.$v;
  }

  if (!isset(self::$urls[$key]) {
    $urls[$key]=create_link($presenterAction, $fooArr); //nahradit za generování linku
  }

  $realLink=$urls[$key];
  foreach($params as $k=>$v) {
      $realLink=str_replace($fooArr[$k], $v, $realLink);
  }

  echo $realLink;
}
}
```

latte:
{cachedLink "Presenter:action" ["id"=>"123", "slug"=>$slug]}

psáno z hlavy, tak to může být trochu buggy

**Comment by JanSuchanek** [comment]
Ju fajné vyzkouším díky moc, je paráda že se může komentovat Davidovo školení.

Škoda, že na Gitu není takhle pěkně i jeho první školení.

**Comment by trejjam** [comment]
Toho jsem se bohužel nezúčastnil :) tehdá jsem toho o GITu moc nevěděl (čti nic než moc :) ) tak by mě takovýto záznam možná ani nenapadl :)

**Comment by JanSuchanek** [comment]
:+1: No ještě že jsi to zaznamenával zachvilku bych si pamatoval uplný prd.

**Comment by TomasVotruba** [comment]
@JanSuchanek Příklad, který uvádíš, je záležitost routeru (metody filterIn/filterOut). Řešit to v latte je zbytečný overkill. Makro se hodí spíše na syntax sugar `{input ...}`, `{inputError }` apod.

OT: Markdown umí pěkně formátovat, mrkněte na "Markdown supported" u komentáře.

``` smarty


{foreach $articles as $article}
    <a n:href="Article:default, slug => $article->slug">...</a>
{/}
```

**Comment by JanSuchanek** [comment]
@TomasVotruba ok, jak píše Trejjam : "nečisté" řešení, které ale rozhodně na rychlosti přidá
